# coding: utf-8

"""
Influx API Service.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

OpenAPI spec version: 0.1.0
Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PkgSummaryErrors(object):
    """NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'kind': 'str',
        'reason': 'str',
        'fields': 'list[str]',
        'indexes': 'list[int]'
    }

    attribute_map = {
        'kind': 'kind',
        'reason': 'reason',
        'fields': 'fields',
        'indexes': 'indexes'
    }

    def __init__(self, kind=None, reason=None, fields=None, indexes=None):  # noqa: E501,D401,D403
        """PkgSummaryErrors - a model defined in OpenAPI."""  # noqa: E501
        self._kind = None
        self._reason = None
        self._fields = None
        self._indexes = None
        self.discriminator = None

        if kind is not None:
            self.kind = kind
        if reason is not None:
            self.reason = reason
        if fields is not None:
            self.fields = fields
        if indexes is not None:
            self.indexes = indexes

    @property
    def kind(self):
        """Get the kind of this PkgSummaryErrors.

        :return: The kind of this PkgSummaryErrors.
        :rtype: str
        """  # noqa: E501
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Set the kind of this PkgSummaryErrors.

        :param kind: The kind of this PkgSummaryErrors.
        :type: str
        """  # noqa: E501
        self._kind = kind

    @property
    def reason(self):
        """Get the reason of this PkgSummaryErrors.

        :return: The reason of this PkgSummaryErrors.
        :rtype: str
        """  # noqa: E501
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Set the reason of this PkgSummaryErrors.

        :param reason: The reason of this PkgSummaryErrors.
        :type: str
        """  # noqa: E501
        self._reason = reason

    @property
    def fields(self):
        """Get the fields of this PkgSummaryErrors.

        :return: The fields of this PkgSummaryErrors.
        :rtype: list[str]
        """  # noqa: E501
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Set the fields of this PkgSummaryErrors.

        :param fields: The fields of this PkgSummaryErrors.
        :type: list[str]
        """  # noqa: E501
        self._fields = fields

    @property
    def indexes(self):
        """Get the indexes of this PkgSummaryErrors.

        :return: The indexes of this PkgSummaryErrors.
        :rtype: list[int]
        """  # noqa: E501
        return self._indexes

    @indexes.setter
    def indexes(self, indexes):
        """Set the indexes of this PkgSummaryErrors.

        :param indexes: The indexes of this PkgSummaryErrors.
        :type: list[int]
        """  # noqa: E501
        self._indexes = indexes

    def to_dict(self):
        """Return the model properties as a dict."""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Return the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Return true if both objects are equal."""
        if not isinstance(other, PkgSummaryErrors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Return true if both objects are not equal."""
        return not self == other
