# coding: utf-8

"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401


class TemplateApplyRemotes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'content_type': 'str'
    }

    attribute_map = {
        'url': 'url',
        'content_type': 'contentType'
    }

    def __init__(self, url=None, content_type=None):  # noqa: E501,D401,D403
        """TemplateApplyRemotes - a model defined in OpenAPI."""  # noqa: E501
        self._url = None
        self._content_type = None
        self.discriminator = None

        self.url = url
        if content_type is not None:
            self.content_type = content_type

    @property
    def url(self):
        """Get the url of this TemplateApplyRemotes.

        :return: The url of this TemplateApplyRemotes.
        :rtype: str
        """  # noqa: E501
        return self._url

    @url.setter
    def url(self, url):
        """Set the url of this TemplateApplyRemotes.

        :param url: The url of this TemplateApplyRemotes.
        :type: str
        """  # noqa: E501
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501
        self._url = url

    @property
    def content_type(self):
        """Get the content_type of this TemplateApplyRemotes.

        :return: The content_type of this TemplateApplyRemotes.
        :rtype: str
        """  # noqa: E501
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Set the content_type of this TemplateApplyRemotes.

        :param content_type: The content_type of this TemplateApplyRemotes.
        :type: str
        """  # noqa: E501
        self._content_type = content_type

    def to_dict(self):
        """Return the model properties as a dict."""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Return the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Return true if both objects are equal."""
        if not isinstance(other, TemplateApplyRemotes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Return true if both objects are not equal."""
        return not self == other
