# coding: utf-8

"""
    Influx API Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import influxdb2
from influxdb2.api.setup_api import SetupApi  # noqa: E501
from influxdb2.rest import ApiException


class TestSetupApi(unittest.TestCase):
    """SetupApi unit test stubs"""

    def setUp(self):
        self.api = influxdb2.api.setup_api.SetupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_setup(self):
        """Test case for get_setup

        check if database has default user, org, bucket created, returns true if not.  # noqa: E501
        """
        pass

    def test_post_setup(self):
        """Test case for post_setup

        post onboarding request, to setup initial user, org and bucket  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
