# coding: utf-8

"""
    Influx API Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import influxdb2
from influxdb2.api.buckets_api import BucketsApi  # noqa: E501
from influxdb2.rest import ApiException


class TestBucketsApi(unittest.TestCase):
    """BucketsApi unit test stubs"""

    def setUp(self):
        self.api = influxdb2.api.buckets_api.BucketsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_buckets_id(self):
        """Test case for delete_buckets_id

        Delete a bucket  # noqa: E501
        """
        pass

    def test_delete_buckets_id_labels_id(self):
        """Test case for delete_buckets_id_labels_id

        delete a label from a bucket  # noqa: E501
        """
        pass

    def test_delete_buckets_id_members_id(self):
        """Test case for delete_buckets_id_members_id

        removes a member from an bucket  # noqa: E501
        """
        pass

    def test_delete_buckets_id_owners_id(self):
        """Test case for delete_buckets_id_owners_id

        removes an owner from a bucket  # noqa: E501
        """
        pass

    def test_get_buckets(self):
        """Test case for get_buckets

        List all buckets  # noqa: E501
        """
        pass

    def test_get_buckets_id(self):
        """Test case for get_buckets_id

        Retrieve a bucket  # noqa: E501
        """
        pass

    def test_get_buckets_id_labels(self):
        """Test case for get_buckets_id_labels

        list all labels for a bucket  # noqa: E501
        """
        pass

    def test_get_buckets_id_logs(self):
        """Test case for get_buckets_id_logs

        Retrieve operation logs for a bucket  # noqa: E501
        """
        pass

    def test_get_buckets_id_members(self):
        """Test case for get_buckets_id_members

        List all users with member privileges for a bucket  # noqa: E501
        """
        pass

    def test_get_buckets_id_owners(self):
        """Test case for get_buckets_id_owners

        List all owners of a bucket  # noqa: E501
        """
        pass

    def test_get_sources_id_buckets(self):
        """Test case for get_sources_id_buckets

        Get a sources buckets (will return dbrps in the form of buckets if it is a v1 source)  # noqa: E501
        """
        pass

    def test_patch_buckets_id(self):
        """Test case for patch_buckets_id

        Update a bucket  # noqa: E501
        """
        pass

    def test_post_buckets(self):
        """Test case for post_buckets

        Create a bucket  # noqa: E501
        """
        pass

    def test_post_buckets_id_labels(self):
        """Test case for post_buckets_id_labels

        add a label to a bucket  # noqa: E501
        """
        pass

    def test_post_buckets_id_members(self):
        """Test case for post_buckets_id_members

        Add bucket member  # noqa: E501
        """
        pass

    def test_post_buckets_id_owners(self):
        """Test case for post_buckets_id_owners

        Add bucket owner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
