version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
  configuration: docs/conf.py

python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .
    extra_requirements:
      - async
      - extra
      - ciso