# coding: utf-8

"""
    Influx API Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Axes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'x': 'Axis',
        'y': 'Axis',
        'y2': 'Axis'
    }

    attribute_map = {
        'x': 'x',
        'y': 'y',
        'y2': 'y2'
    }

    def __init__(self, x=None, y=None, y2=None):  # noqa: E501
        """Axes - a model defined in OpenAPI"""  # noqa: E501

        self._x = None
        self._y = None
        self._y2 = None
        self.discriminator = None

        if x is not None:
            self.x = x
        if y is not None:
            self.y = y
        if y2 is not None:
            self.y2 = y2

    @property
    def x(self):
        """Gets the x of this Axes.  # noqa: E501


        :return: The x of this Axes.  # noqa: E501
        :rtype: Axis
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this Axes.


        :param x: The x of this Axes.  # noqa: E501
        :type: Axis
        """

        self._x = x

    @property
    def y(self):
        """Gets the y of this Axes.  # noqa: E501


        :return: The y of this Axes.  # noqa: E501
        :rtype: Axis
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this Axes.


        :param y: The y of this Axes.  # noqa: E501
        :type: Axis
        """

        self._y = y

    @property
    def y2(self):
        """Gets the y2 of this Axes.  # noqa: E501


        :return: The y2 of this Axes.  # noqa: E501
        :rtype: Axis
        """
        return self._y2

    @y2.setter
    def y2(self, y2):
        """Sets the y2 of this Axes.


        :param y2: The y2 of this Axes.  # noqa: E501
        :type: Axis
        """

        self._y2 = y2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Axes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
