# coding: utf-8

"""
    Influx API Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Dashboards(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'links': 'Links',
        'dashboards': 'list[Dashboard]'
    }

    attribute_map = {
        'links': 'links',
        'dashboards': 'dashboards'
    }

    def __init__(self, links=None, dashboards=None):  # noqa: E501
        """Dashboards - a model defined in OpenAPI"""  # noqa: E501

        self._links = None
        self._dashboards = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if dashboards is not None:
            self.dashboards = dashboards

    @property
    def links(self):
        """Gets the links of this Dashboards.  # noqa: E501


        :return: The links of this Dashboards.  # noqa: E501
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Dashboards.


        :param links: The links of this Dashboards.  # noqa: E501
        :type: Links
        """

        self._links = links

    @property
    def dashboards(self):
        """Gets the dashboards of this Dashboards.  # noqa: E501


        :return: The dashboards of this Dashboards.  # noqa: E501
        :rtype: list[Dashboard]
        """
        return self._dashboards

    @dashboards.setter
    def dashboards(self, dashboards):
        """Sets the dashboards of this Dashboards.


        :param dashboards: The dashboards of this Dashboards.  # noqa: E501
        :type: list[Dashboard]
        """

        self._dashboards = dashboards

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Dashboards):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
