# coding: utf-8

"""
    Influx API Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DocumentUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'meta': 'DocumentMeta',
        'content': 'object'
    }

    attribute_map = {
        'meta': 'meta',
        'content': 'content'
    }

    def __init__(self, meta=None, content=None):  # noqa: E501
        """DocumentUpdate - a model defined in OpenAPI"""  # noqa: E501

        self._meta = None
        self._content = None
        self.discriminator = None

        if meta is not None:
            self.meta = meta
        if content is not None:
            self.content = content

    @property
    def meta(self):
        """Gets the meta of this DocumentUpdate.  # noqa: E501


        :return: The meta of this DocumentUpdate.  # noqa: E501
        :rtype: DocumentMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this DocumentUpdate.


        :param meta: The meta of this DocumentUpdate.  # noqa: E501
        :type: DocumentMeta
        """

        self._meta = meta

    @property
    def content(self):
        """Gets the content of this DocumentUpdate.  # noqa: E501


        :return: The content of this DocumentUpdate.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this DocumentUpdate.


        :param content: The content of this DocumentUpdate.  # noqa: E501
        :type: object
        """

        self._content = content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
