# coding: utf-8

"""
    Influx API Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class OperationLog(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'time': 'datetime',
        'user_id': 'str',
        'links': 'OperationLogLinks'
    }

    attribute_map = {
        'description': 'description',
        'time': 'time',
        'user_id': 'userID',
        'links': 'links'
    }

    def __init__(self, description=None, time=None, user_id=None, links=None):  # noqa: E501
        """OperationLog - a model defined in OpenAPI"""  # noqa: E501

        self._description = None
        self._time = None
        self._user_id = None
        self._links = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if time is not None:
            self.time = time
        if user_id is not None:
            self.user_id = user_id
        if links is not None:
            self.links = links

    @property
    def description(self):
        """Gets the description of this OperationLog.  # noqa: E501

        A description of the event that occurred.  # noqa: E501

        :return: The description of this OperationLog.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OperationLog.

        A description of the event that occurred.  # noqa: E501

        :param description: The description of this OperationLog.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def time(self):
        """Gets the time of this OperationLog.  # noqa: E501

        Time event occurred, RFC3339Nano.  # noqa: E501

        :return: The time of this OperationLog.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this OperationLog.

        Time event occurred, RFC3339Nano.  # noqa: E501

        :param time: The time of this OperationLog.  # noqa: E501
        :type: datetime
        """

        self._time = time

    @property
    def user_id(self):
        """Gets the user_id of this OperationLog.  # noqa: E501

        ID of the user who operated the event.  # noqa: E501

        :return: The user_id of this OperationLog.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this OperationLog.

        ID of the user who operated the event.  # noqa: E501

        :param user_id: The user_id of this OperationLog.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def links(self):
        """Gets the links of this OperationLog.  # noqa: E501


        :return: The links of this OperationLog.  # noqa: E501
        :rtype: OperationLogLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this OperationLog.


        :param links: The links of this OperationLog.  # noqa: E501
        :type: OperationLogLinks
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OperationLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
